name: Update Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest
    steps:
      - uses: siddharth2016/readme-quote@main
