name: Update README.md

on:
  workflow_dispatch:
  schedule:
    # Runs at 1 UTC everyday
    - cron: "0 1 * * *"
jobs:
  build:
    name: Update README.md
    runs-on: ubuntu-latest
    
    env:
     email: ${{secrets.email}}
     userName: ${{secrets.userName}}
    steps:
    - name: Checkout current repository to Master
      uses: actions/checkout@v3
    - name: Setup NodeJs
      uses: actions/setup-node@v3
      with:
        node-version: "17.x"
    - name: Cache dependencies and build outputs
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{runner.os}}-js-${{hashFiles('package-lock.json')}}
    - name: install dependencies
      run: npm install
    - name: fetching
      run: |
        git fetch
    - name: Generate README.md
      run: node index.mjs
    - name: Commit and push the update README.md to the repository
      run: |
        git config --global user.name userName
        git config --global user.email email
        git commit -a -m "Updated README.md"
        git push
